openapi: 3.0.0
info:
  title: HarToOpenApi
  version: 1.0.0
  description: >-
    OpenAPI spec generated from HAR data for localhost on
    2023-10-27T09:58:03.963Z
paths:
  /api/v1/users:
    get:
      description: ''
      operationId: getApiV1Users
      parameters:
        - description: skip
          in: query
          name: skip
          schema:
            default: '0'
            example: '0'
            type: string
        - description: limit
          in: query
          name: limit
          schema:
            default: '100'
            example: '100'
            type: string
        - description: Authorization
          in: header
          name: Authorization
          schema:
            default: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9objIxNS5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTgzOTA1ODYsImV4cCI6MTY5ODQzMzc4Nn0.BpO49F3lwLwsqPSHJoOUjB4zk8sFJ50wjq04F9SVf-I
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9objIxNS5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTgzOTA1ODYsImV4cCI6MTY5ODQzMzc4Nn0.BpO49F3lwLwsqPSHJoOUjB4zk8sFJ50wjq04F9SVf-I
            type: string
      responses:
        '200':
          content:
            application/json:
              example:
                code: 200
                data:
                  - created_at: '2023-10-27T07:08:39.602Z'
                    email: john215.doe@example.com
                    first_name: John
                    id: 1
                    last_name: Doe
                    role: user
                    status: inactive
                    updated_at: '2023-10-27T07:08:39.602Z'
                    username: john_doe5
                message: Success
                status: true
              schema:
                additionalProperties: false
                properties:
                  code:
                    type: integer
                  data:
                    items:
                      additionalProperties: false
                      properties:
                        created_at:
                          format: date-time
                          type: string
                        email:
                          type: string
                        first_name:
                          type: string
                        id:
                          type: integer
                        last_name:
                          type: string
                        role:
                          type: string
                        status:
                          type: string
                        updated_at:
                          format: date-time
                          type: string
                        username:
                          type: string
                      required: []
                      title: Datum
                      type: object
                    type: array
                  message:
                    type: string
                  status:
                    type: boolean
                required: []
                title: APIV1UsersGetRequest
                type: object
          description: ''
      security:
        - Authorization: []
      summary: Get Api V 1 Users
    parameters: []
  /api/v1/users/:
    parameters: []
    post:
      description: ''
      operationId: postApiV1Users
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              email: john215.doe@example.com
              first_name: John
              last_name: Doe
              password: SecureP@ssw0rd
              role: user
              username: john_doe5
            schema:
              additionalProperties: false
              properties:
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
                role:
                  type: string
                username:
                  type: string
              required: []
              title: APIV1UsersPostRequest
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                code: 200
                data:
                  created_at: '2023-10-27T07:08:39.602Z'
                  email: john215.doe@example.com
                  first_name: John
                  id: 1
                  last_name: Doe
                  role: user
                  status: inactive
                  updated_at: '2023-10-27T07:08:39.602Z'
                  username: john_doe5
                message: Success
                status: true
              schema:
                additionalProperties: false
                properties:
                  code:
                    type: integer
                  data:
                    additionalProperties: false
                    properties:
                      created_at:
                        format: date-time
                        type: string
                      email:
                        type: string
                      first_name:
                        type: string
                      id:
                        type: integer
                      last_name:
                        type: string
                      role:
                        type: string
                      status:
                        type: string
                      updated_at:
                        format: date-time
                        type: string
                      username:
                        type: string
                    required: []
                    title: Data
                    type: object
                  message:
                    type: string
                  status:
                    type: boolean
                required: []
                title: APIV1UsersPostRequest
                type: object
          description: ''
      summary: Post Api V 1 Users
  /api/v1/users/login:
    parameters: []
    post:
      description: ''
      operationId: postApiV1UsersLogin
      parameters:
        - description: Authorization
          in: header
          name: Authorization
          schema:
            default: 'Bearer '
            example: 'Bearer '
            type: string
      requestBody:
        content:
          application/json:
            example:
              email: john215.doe@example.com
              password: SecureP@ssw0rd
            schema:
              additionalProperties: false
              properties:
                email:
                  type: string
                password:
                  type: string
              required: []
              title: APIV1UsersLoginPostRequest
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                code: 200
                data:
                  token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9objIxNS5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTgzOTA1ODYsImV4cCI6MTY5ODQzMzc4Nn0.BpO49F3lwLwsqPSHJoOUjB4zk8sFJ50wjq04F9SVf-I
                message: Success
                status: true
              schema:
                additionalProperties: false
                properties:
                  code:
                    type: integer
                  data:
                    additionalProperties: false
                    properties:
                      token:
                        type: string
                    required: []
                    title: Data
                    type: object
                  message:
                    type: string
                  status:
                    type: boolean
                required: []
                title: APIV1UsersLoginPostRequest
                type: object
          description: ''
      security:
        - Authorization: []
      summary: Post Api V 1 Users Login
servers:
  - url: /
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
